name: car_rental_project
description: "A new Flutter project about the car rents by the Softsnips"


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1




  #---------------- Packages start ------------#


dependencies:
  flutter:
    sdk: flutter


  #Icons
  cupertino_icons: ^1.0.8
  #state management#
  get: ^4.7.2


  #------- packages end ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true


  # ---------- Local Assets --------- #
  assets:
    - assets/logo/
    - assets/icons/
    - assets/Images/










